---

- name: "cert-dirs: Create public directories {{ certificate_dir }}"
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ certificate_owner }}"
    group: "{{ certificate_group }}"
    mode: "{{ certificate_dir_mode }}"
  loop:
    - "{{ certificate_dir }}"
    - "{{ certificate_dir }}/certs"
    - "{{ certificate_dir }}/csr"

- name: "cert-dirs: Link certs to crt in {{ certificate_dir }}"
  file:
    state: link
    src: "{{ certificate_dir }}/certs"
    dest: "{{ certificate_dir }}/crt"
    owner: "{{ certificate_owner }}"
    group: "{{ certificate_group }}"
  when: certificate_link_crt|bool

- name: "cert-dirs: Create {{ certificate_dir }}/private"
  file:
    state: directory
    path: "{{ certificate_private_dir }}"
    owner: "{{ certificate_private_owner }}"
    group: "{{ certificate_private_group }}"
    mode: "{{ certificate_private_dir_mode }}"

# EOF
...
