---

- name: "cert-openssl-csr-info: Get information on OpenSSL Certificate Signing Requests (CSR)."
  openssl_csr_info:
    path: "{{ certificate_dir_csr }}/{{ item.csr }}"
    select_crypto_backend: "{{ item.backend|default(certificate_default_backend) }}"
  register: certificate_result_csr_info
  loop: "{{ certificate_data }}"
  when: not ansible_check_mode

- name: "cert-openssl-csr-info: Display information on OpenSSL Certificate Signing Requests (CSR)."
  debug:
    var: certificate_result_csr_info
  when: certificate_result_csr_info is defined

# EOF
...
