---
# certificate tasks

- import_tasks: vars.yml
  tags: [certificate_vars, always]

- import_tasks: help.yml
  tags: always

- import_tasks: debug.yml
  when: certificate_debug|bool
  tags: [certificate_debug, always]

- import_tasks: packages.yml
  when: certificate_install|bool
  tags: certificate_packages

- import_tasks: sanity.yml
  when: certificate_sanity|bool
  tags: certificate_sanity

- import_tasks: cert-dirs.yml
  tags: certificate_dirs

- import_tasks: cert-command.yml
  tags: certificate_command

- import_tasks: cert-openssl-privatekey.yml
  tags:
    - certificate_openssl_privatekey
    - certificate_openssl

- import_tasks: cert-openssl-privatekey-info.yml
  tags: certificate_openssl_privatekey_info

- import_tasks: cert-openssl-csr.yml
  tags:
    - certificate_openssl_csr
    - certificate_openssl

- import_tasks: cert-openssl-csr-info.yml
  tags: certificate_openssl_csr_info

- import_tasks: cert-openssl-certificate.yml
  tags:
    - certificate_openssl_certificate
    - certificate_openssl

- import_tasks: cert-openssl-certificate-info.yml
  tags: certificate_openssl_certificate_info

# EOF
...
