---
# certificate tasks

- import_tasks: sanity.yml
  tags: certificate_sanity

- import_tasks: vars.yml
  tags: [certificate_vars, always]

- import_tasks: debug.yml
  when: certificate_debug|bool
  tags: [certificate_debug, always]

- import_tasks: packages.yml
  when: certificate_install|bool
  tags: certificate_packages

- import_tasks: cert-dirs.yml
  tags: certificate_dirs

- import_tasks: cert-command.yml
  tags: certificate_command

- import_tasks: cert-self-signed.yml
  tags: certificate_self_signed

- import_tasks: cert-acme.yml
  tags: certificate_acme

# EOF
...
