---
# certificate tasks

- import_tasks: vars.yml
  tags: [certificate_vars, always]

- import_tasks: debug.yml
  when: certificate_debug|bool
  tags: [certificate_debug, always]

- import_tasks: packages.yml
  when: certificate_install|bool
  tags: certificate_packages

- import_tasks: sanity.yml
  when: certificate_sanity|bool
  tags: certificate_sanity

- import_tasks: cert-dirs.yml
  tags: certificate_dirs

- import_tasks: cert-command.yml
  tags: certificate_command

- import_tasks: cert-openssl-privatekey.yml
  tags: certificate-openssl-privatekey

- import_tasks: cert-openssl-csr.yml
  tags: certificate-openssl-csr

- import_tasks: cert-openssl-certificate.yml
  tags: certificate-openssl-certificate

# EOF
...
