---
# certificate tasks

- import_tasks: vars.yml
  tags: certificate_vars

- import_tasks: debug.yml
  when: certificate_debug
  tags: certificate_debug

- import_tasks: packages.yml
  tags: certificate_packages

- import_tasks: cert-dirs.yml
  tags: certificate_dirs

- import_tasks: cert-self-signed.yml
  tags: certificate_self_signed

- import_tasks: cert-acme.yml
  tags: certificate_acme

# EOF
...
